# Sources
source 'https://github.com/adxcorp/AdxLibrary_iOS_Release.git'
source 'https://github.com/CocoaPods/Specs.git'      

# Uncomment the next line to define a global platform for your project
use_frameworks!
platform :ios, '11.0'

# firebase
#pod 'Firebase/AdMob'
pod 'Firebase/Analytics', '10.13.0'
pod 'Firebase/RemoteConfig', '10.13.0'
pod 'Firebase/DynamicLinks', '10.13.0'
pod 'Firebase/Messaging', '10.13.0'
pod 'Firebase/Performance', '10.13.0'
pod 'Firebase/Crashlytics', '10.13.0'

# tracking
pod 'AppsFlyerFramework', '6.2.4'
# facebook
pod 'FBSDKCoreKit', '14.1.0'

pod 'ADXLibrary/Rewarded', '2.4.0'

# 20220621 adx 변경으로 인해 주석 처리
# pod 'Google-Mobile-Ads-SDK', '8.2.0.1'
# pod 'GoogleMobileAdsMediationAppLovin', '10.0.1.0'
# pod 'GoogleMobileAdsMediationFacebook', '6.6.0.0'
# pod 'GoogleMobileAdsMediationAdColony', '4.5.0.0'
# pod 'GoogleMobileAdsMediationUnity', '3.6.0.0'
# pod 'GoogleMobileAdsMediationIronSource', '7.1.2.0'
# pod 'GoogleMobileAdsMediationFyber', '7.8.1.0'

# IronSource offerwall
#pod 'IronSourceSDK', '6.15.0.1'


target 'FantasyClicker-mobile' do
  # Comment the next line if you don't want to use dynamic frameworks
  #use_frameworks!

  # Pods for FantasyClicker-mobile

end

post_install do |installer|
    installer.generated_projects.each do |project|
          project.targets.each do |target|
              target.build_configurations.each do |config|
                  config.build_settings['IPHONEOS_DEPLOYMENT_TARGET'] = '11.0'
                  config.build_settings["EXCLUDED_ARCHS[sdk=iphonesimulator*]"] = "arm64"
               end
          end
   end
end
