LOCAL_PATH := $(call my-dir)

include $(CLEAR_VARS)

LOCAL_MODULE := MyGame_shared

LOCAL_MODULE_FILENAME := libMyGame

CLASSES_PATH := $(LOCAL_PATH)/../../../Classes
CLASSES_DIRS := $(shell find $(CLASSES_PATH) -type d)

CLASSES_CPPFILE_TEMP := $(shell find $(CLASSES_PATH) -name *.cpp)
CLASSES_CPPFILE_TEMP := $(sort $(CLASSES_CPPFILE_TEMP))
CLASSES_CPPFILE := $(subst $(LOCAL_PATH)/,,$(CLASSES_CPPFILE_TEMP))

LOCAL_SRC_FILES := hellocpp/main.cpp \
    				$(CLASSES_CPPFILE)

LOCAL_C_INCLUDES := $(CLASSES_DIRS)

# _COCOS_HEADER_ANDROID_BEGIN
# _COCOS_HEADER_ANDROID_END


LOCAL_STATIC_LIBRARIES := cc_static

# _COCOS_LIB_ANDROID_BEGIN
# _COCOS_LIB_ANDROID_END

include $(BUILD_SHARED_LIBRARY)

$(call import-module, cocos)

# _COCOS_LIB_IMPORT_ANDROID_BEGIN
# _COCOS_LIB_IMPORT_ANDROID_END
